# Generated by Django 4.2.16 on 2024-12-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='tipo',
            field=models.CharField(blank=True, choices=[('entrada segundaria grupo 1 izquierda', 'entrada segundaria grupo 1 izquierda'), ('entrada segundaria grupo 1 derecha', 'entrada segundaria grupo 1 derecha'), ('entrada segundaria grupo 2 izquierda', 'entrada segundaria grupo 2 izquierda'), ('entrada segundaria grupo 2 derecha', 'entrada segundaria grupo 2 derecha'), ('entrada segundaria grupo 3 izquierda', 'entrada segundaria grupo 3 izquierda'), ('entrada segundaria grupo 3 derecha', 'entrada segundaria grupo 3 derecha'), ('entrada segundaria grupo 4 izquierda', 'entrada segundaria grupo 4 izquierda'), ('entrada segundaria grupo 4 derecha', 'entrada segundaria grupo 4 derecha'), ('entrada segundaria grupo 5 izquierda', 'entrada segundaria grupo 5 izquierda'), ('entrada segundaria grupo 5 derecha', 'entrada segundaria grupo 5 derecha'), ('entrada grupo 1 larga', 'entrada grupo 1 larga'), ('entrada grupo 2 larga', 'entrada grupo 2 larga')], help_text='Tipo de local dentro de los grupos predefinidos', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Referencia al nivel superior del local', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subniveles', to='locales.local'),
        ),
        migrations.AlterField(
            model_name='local',
            name='precio_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locales', to='locales.preciobase'),
        ),
    ]
