# Generated by Django 4.2.16 on 2024-12-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='parent',
        ),
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.CharField(blank=True, choices=[('entrada segundaria grupo 1 izquierda', 'Entrada secundaria grupo 1 izquierda'), ('entrada segundaria grupo 1 derecha', 'Entrada secundaria grupo 1 derecha'), ('entrada segundaria grupo 2 izquierda', 'Entrada secundaria grupo 2 izquierda'), ('entrada segundaria grupo 2 derecha', 'Entrada secundaria grupo 2 derecha'), ('entrada segundaria grupo 3 izquierda', 'Entrada secundaria grupo 3 izquierda'), ('entrada segundaria grupo 3 derecha', 'Entrada secundaria grupo 3 derecha'), ('entrada segundaria grupo 4 izquierda', 'Entrada secundaria grupo 4 izquierda'), ('entrada segundaria grupo 4 derecha', 'Entrada secundaria grupo 4 derecha'), ('entrada grupo 1 larga', 'Entrada grupo 1 larga'), ('entrada grupo 2 larga', 'Entrada grupo 2 larga')], help_text='Escoja el tipo', max_length=50, null=True),
        ),
    ]
