# Generated by Django 4.2.16 on 2024-12-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='area',
            field=models.CharField(help_text='Área total (puede incluir unidades, ejemplo: 15 m²).', max_length=50),
        ),
        migrations.AlterField(
            model_name='local',
            name='perimetro',
            field=models.CharField(help_text='Perímetro (puede incluir unidades, ejemplo: 25 m).', max_length=50),
        ),
    ]
