# Generated by Django 4.2.16 on 2024-12-20 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='subnivel_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subniveles', to='locales.local'),
        ),
    ]
