# Generated by Django 4.2.16 on 2024-12-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='tiene_subniveles',
        ),
    ]
