# Generated by Django 4.2.16 on 2025-08-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_alter_local_area_alter_local_perimetro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre único de la galería', max_length=255, unique=True)),
                ('static', models.BooleanField(default=False, help_text='Indica si la galería es estática (no se puede modificar)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la galería')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Galería',
                'verbose_name_plural': 'Galerías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, help_text='Título opcional de la imagen', max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la imagen', null=True)),
                ('imagen', models.ImageField(help_text='Imagen de la galería', upload_to='galeria_images/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización de la imagen en la galería')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la imagen está activa y visible')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Fecha de subida de la imagen')),
                ('galeria', models.ForeignKey(help_text='Galería a la que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='locales.galeria')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['galeria', 'orden', 'fecha_subida'],
            },
        ),
    ]
