# Generated by Django 4.2.16 on 2024-12-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_remove_local_parent_alter_local_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='tiene_subniveles',
            field=models.BooleanField(default=False, help_text='Indica si la zona tiene subniveles asociados'),
        ),
    ]
