# Generated by Django 4.2.16 on 2024-12-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_alter_local_subnivel_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='Disponible', help_text='Estado del local (disponible, reservado, vendido).', max_length=20),
        ),
    ]
