# Generated by Django 4.2.16 on 2024-12-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_alter_local_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='subnivel_de',
            field=models.ForeignKey(blank=True, help_text='Zona principal que permite subniveles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subniveles', to='locales.zona'),
        ),
    ]
