# Generated by Django 4.2.16 on 2025-08-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_galeria_imagengaleria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={},
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='static',
        ),
        migrations.AddField(
            model_name='galeria',
            name='files',
            field=models.CharField(default='', help_text='Archivos de la galería', max_length=255),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='name',
            field=models.CharField(help_text='Nombre de la galería', max_length=255),
        ),
        migrations.DeleteModel(
            name='ImagenGaleria',
        ),
    ]
