# Generated by Django 4.2.16 on 2024-12-04 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_zona_tiene_subniveles'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='subnivel_de',
            field=models.ForeignKey(blank=True, help_text='Zona de la que este local es un subnivel, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subniveles', to='locales.zona'),
        ),
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.CharField(blank=True, choices=[('entrada segundaria grupo 1 izquierda', 'Entrada secundaria grupo 1 izquierda'), ('entrada segundaria grupo 1 derecha', 'Entrada secundaria grupo 1 derecha'), ('entrada segundaria grupo 2 izquierda', 'Entrada secundaria grupo 2 izquierda'), ('entrada segundaria grupo 2 derecha', 'Entrada secundaria grupo 2 derecha'), ('entrada segundaria grupo 3 izquierda', 'Entrada secundaria grupo 3 izquierda'), ('entrada segundaria grupo 3 derecha', 'Entrada secundaria grupo 3 derecha'), ('entrada segundaria grupo 4 izquierda', 'Entrada secundaria grupo 4 izquierda'), ('entrada segundaria grupo 4 derecha', 'Entrada secundaria grupo 4 derecha'), ('entrada grupo 1 larga', 'Entrada grupo 1 larga'), ('entrada grupo 2 larga', 'Entrada grupo 2 larga')], help_text='Escoja el tipo', max_length=36, null=True),
        ),
    ]
