# Generated by Django 4.2.16 on 2025-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0004_alter_galeria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='files',
            field=models.ImageField(blank=True, help_text='Imagen de la galería', null=True, upload_to='galeria_images/'),
        ),
    ]
