# Generated by Django 4.2.16 on 2024-12-11 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0005_remove_local_unique_local_per_zona_metraje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(help_text='Código del subnivel.', max_length=50)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del subnivel.', max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponible', help_text='Estado del subnivel (disponible, reservado, vendido).', max_length=20)),
                ('metraje', models.CharField(help_text='Metraje del subnivel.', max_length=50)),
                ('image', models.CharField(default='../assets/tipos_locales/mediano.png', help_text='Imagen del subnivel.', max_length=255)),
                ('local_principal', models.ForeignKey(help_text='Local principal al que pertenecen los subniveles.', on_delete=django.db.models.deletion.CASCADE, related_name='subniveles', to='locales.local')),
            ],
        ),
    ]
