# Generated by Django 4.2.16 on 2024-12-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0006_subnivel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subnivelrelacion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subnivelrelacion',
            name='subnivel_1',
        ),
        migrations.RemoveField(
            model_name='subnivelrelacion',
            name='subnivel_2',
        ),
        migrations.RemoveField(
            model_name='subnivelrelacion',
            name='zona_principal',
        ),
        migrations.AddField(
            model_name='local',
            name='subniveles',
            field=models.JSONField(blank=True, help_text='Datos JSON para subniveles de este local', null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.CharField(blank=True, choices=[('entrada segundaria grupo 1 izquierda', 'Entrada segundaria grupo 1 izquierda'), ('entrada segundaria grupo 1 derecha', 'Entrada segundaria grupo 1 derecha'), ('entrada segundaria grupo 2 izquierda', 'Entrada segundaria grupo 2 izquierda'), ('entrada segundaria grupo 2 derecha', 'Entrada segundaria grupo 2 derecha'), ('entrada segundaria grupo 3 izquierda', 'Entrada segundaria grupo 3 izquierda'), ('entrada segundaria grupo 3 derecha', 'Entrada segundaria grupo 3 derecha'), ('entrada segundaria grupo 4 izquierda', 'Entrada segundaria grupo 4 izquierda'), ('entrada segundaria grupo 4 derecha', 'Entrada segundaria grupo 4 derecha'), ('entrada grupo 1 larga', 'Entrada grupo 1 larga'), ('entrada grupo 2 larga', 'Entrada grupo 2 larga')], help_text='Escoja el tipo', max_length=36, null=True),
        ),
        migrations.DeleteModel(
            name='Subnivel',
        ),
        migrations.DeleteModel(
            name='SubnivelRelacion',
        ),
    ]
