# Generated by Django 4.2.16 on 2024-12-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpinversion',
            name='acepta_terminos',
        ),
        migrations.RemoveField(
            model_name='cpinversion',
            name='tipo_local',
        ),
    ]
