# Generated by Django 4.2.16 on 2025-01-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contac', '0002_alter_cpinversion_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpinversion',
            name='objetivo_inversion',
            field=models.CharField(blank=True, choices=[('comercial', 'Comercial'), ('inversion', 'Inversión')], max_length=50),
        ),
    ]
