# Generated by Django 4.2.16 on 2025-10-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('asesor', 'Asesor'), ('staff', 'Staff'), ('cliente', 'Cliente')], help_text='Tipo de rol asignado al usuario', max_length=80, unique=True),
        ),
    ]
