# Generated by Django 4.2.16 on 2025-10-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'Ya existe un usuario con ese nombre.'}, help_text='150 caracteres o menos. Letras, dígitos y @/./+/-/_ permitidos.', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
