# Generated by Django 4.2.16 on 2025-10-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Tipo de rol asignado al usuario', max_length=80, unique=True),
        ),
    ]
